- examples/bar.html
- src/js/charts/types/bar.js
Fixes https://github.com/globeandmail/chart-tool/issues/14.
> fixes bar height spacing issue

- meteor/client/stylesheets/partials/_chart-archive.scss
- meteor/client/stylesheets/partials/_chart-edit.scss
- meteor/client/templates/chart-archive/chart-archive.html
- meteor/client/templates/chart-archive/chart-archive.js
- meteor/client/templates/chart-show/chart-show.js
Fixes https://github.com/globeandmail/chart-tool/issues/29.
> fixes tag width bug, removes data and share buttons from /show view

- .gitignore
- custom/meteor-custom.scss
- meteor/client/stylesheets/partials/_custom.scss
- meteor/lib/chart-tool/scripts/bundle.js
- meteor/lib/chart-tool/scripts/meteorSettings.js
- meteor/lib/chart-tool/stylesheets/main.css
- src/js/charts/components/axis.js
- src/js/utils/utils.js
> Ordinal-time ticks now display properly

- meteor/client/templates/chart-edit/chart-edit-aside.js
I've taken a stab at writing copy for the missing helper tips and adding sweetalert events.
See #56.
> Added missing helper tips

- meteor/lib/helpers.js
Addresses https://github.com/globeandmail/chart-tool/issues/108.
> Forces formatting to `-` only when a string is only digits and slashes

- gulp/rollup.config.js
- gulp/utils.js
- meteor/client/application.js
- meteor/client/stylesheets/partials/_chart-edit.scss
- meteor/client/templates/chart-edit/chart-edit-preview-single.html
- meteor/client/templates/chart-edit/chart-edit-preview-single.js
- meteor/client/templates/chart-edit/chart-edit-preview.html
- meteor/client/templates/chart-edit/chart-edit-preview.js
- meteor/lib/chart-tool/scripts/chart-tool.js
- src/js/config/env.js
- src/js/index.js
Adds an interstitial frame when charts are updated. A patchy solution to https://github.com/globeandmail/chart-tool/issues/110 until the interface code can be fully rewritten.
> Input delay

- examples/ordinal-line.html
- meteor/lib/chart-tool/scripts/chart-tool.js
- src/js/charts/components/tips.js
- src/js/charts/types/area.js
- src/js/charts/types/line.js
- src/js/charts/types/multiline.js
- src/js/charts/types/stacked-area.js
Fixes ordinal line, area, multiline and stacked area charts, and resolves tips for those chart types
> Ordinal line, area, multiline and stacked area charts

- examples/bar.html
- examples/index.html
- meteor/lib/chart-tool/scripts/chart-tool.js
- src/js/charts/components/tips.js
- src/js/charts/types/bar.js
- src/js/charts/types/column.js
- src/js/charts/types/stacked-bar.js
- src/js/utils/dataparse.js
Adds undefined check to tips.js, and fixes NaN text bug in multiseries bar and column charts
> "NaN" text bug with bar and column charts

- meteor/lib/chart-tool/scripts/chart-tool.js
- src/js/index.js
- src/js/utils/utils.js
Addresses an issue where charts weren't redrawing on the window's `resize` event.
> Fixes a bug where charts weren't redrawing when window was resized

- tutorials/print.md
> Fix broken link

- meteor/lib/routes.js
> Fixes broken Firefox PDF export

- meteor/client/templates/core/header/header.html
- meteor/client/templates/core/header/header.js
- meteor/client/templates/core/navigation/navigation.html
- meteor/client/templates/core/navigation/navigation.js
> Standardizes help link to an anchor tag

- meteor/client/templates/chart-edit/chart-edit-type.js
- meteor/lib/chart-tool/scripts/chart-tool.js
- src/js/charts/components/tips.js
Addresses https://github.com/globeandmail/chart-tool/issues/138 and https://github.com/globeandmail/chart-tool/issues/133.
> Resets index field and better tip handling of 0's vs. n/a's

- meteor/lib/chart-tool/scripts/chart-tool.js
- src/js/charts/components/tips.js
- src/js/utils/dataparse.js
- src/js/utils/utils.js
Refactoring of https://github.com/globeandmail/chart-tool/pull/152 so that the logic lives within `dataparse.js` and `utils.js`.
> Better monthly/annual tips

- custom/meteor-config.js
- meteor/client/stylesheets/partials/_chart-export.scss
- meteor/client/templates/overlays/chart-overlay-print.html
- meteor/client/templates/overlays/chart-overlay-print.js
- meteor/client/templates/pdf/chart-pdf.js
- meteor/lib/chart-tool/scripts/chart-tool.js
- meteor/lib/chart-tool/scripts/settings.js
- meteor/lib/collections/charts-model.js
- meteor/lib/routes.js
Adds millimetre export as an option.
> Print mm export

- meteor/imports/ui/components/Chart.js
Fixes an issue where source line won't unexpand if no source is added.
> Fixes small bug with sourceline

- meteor/imports/modules/chart-tool.js
- meteor/imports/ui/components/ChartAnnotations.js
- meteor/imports/ui/layouts/EditChart.js
Addresses https://github.com/globeandmail/chart-tool/issues/195.
> Fixes annotation subsection state sync issue

- meteor/imports/modules/chart-tool.js
- meteor/imports/ui/components/ChartData.js
- meteor/imports/ui/components/ChartMemo.js
Addresses https://github.com/globeandmail/chart-tool/issues/199.
> Fixes some onblur issues with chart data and memo field

- examples/bar-exportable.html
- meteor/imports/modules/chart-tool.js
- src/js/charts/components/axis.js
- src/js/charts/types/bar.js
Bar chart labels weren't wrapping properly after `wrapText`, this fixes that.
> Adds fixes for bar chart labelling

- meteor/imports/ui/components/Header.js
This would address issue #221.
> The 'Help' link should be an <a> element, not a React Link.

- src/js/index.js
Addressing https://github.com/globeandmail/chart-tool/issues/220.
> Passes chart object to drawFinished and callback
